project:
  type: website

website:
  title: "Home"
  navbar:
    left:
      - href: index.qmd
        text: Alexis Ralli
      - href: papers
        text: papers
      - href: blog
        text: blog
  
  page-footer:
    left: "(c) Alexis Ralli, 2025"
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
